### ISSUE TITLE
{player} for command , Cooldown

### ISSUE THREAD

**Issue by JustJamezX** [DavidFlashCZ/StepCommand#1]
I'd want to do for example "say {player} hi" as console. This will show "{player} hi" instead of for example, "James hi". I also suggest adding a cooldown option for so players can't abuse it. Thank you.

**Comment by DavidFlashCZ** [comment]
Sure, that's a good idea! Thanks for your suggestion :)

**Comment by DavidFlashCZ** [comment]
> I'd want to do for example "say {player} hi" as console. This will show "{player} hi" instead of for example, "James hi". I also suggest adding a cooldown option for so players can't abuse it. Thank you.

done! You can download it right away. Cooldown will be in the next update hopefully.

**Comment by JustJamezX** [comment]
Thank youu!
